benchmark_name: all_approaches_combined
runs:
  - run_identifier: exomiser_phenotype_only
    results_dir: /data/home/bt251044/p2p-work/synthetic_results
    phenopacket_dir: /data/home/bt251044/p2p-work/synthetic_corpus/phenopackets
    gene_analysis: true
    variant_analysis: false
    disease_analysis: false
    threshold:
    score_order: descending
  - run_identifier: claude_phenotype_only
    results_dir: /data/home/bt251044/p2p-work
    phenopacket_dir: /data/home/bt251044/p2p-work/synthetic_corpus/phenopackets
    gene_analysis: true
    variant_analysis: false
    disease_analysis: false
    threshold:
    score_order: descending
  - run_identifier: claude_sonnet_exomiser_assisted
    results_dir: /data/home/bt251044/p2p-work/exomiser_assisted_sonnet_run
    phenopacket_dir: /data/home/bt251044/p2p-work/synthetic_corpus/phenopackets
    gene_analysis: true
    variant_analysis: false
    disease_analysis: false
    threshold:
    score_order: descending
plot_customisation:
  gene_plots:
    plot_type: bar_cumulative
    rank_plot_title:
    roc_curve_title:
    precision_recall_title:
  disease_plots:
    plot_type: bar_cumulative
    rank_plot_title:
    roc_curve_title:
    precision_recall_title:
  variant_plots:
    plot_type: bar_cumulative
    rank_plot_title:
    roc_curve_title:
    precision_recall_title:
